
package unipacifico.edu.pasantia.presentacion;


import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import unipacifico.edu.pasantia.persistencia.PasantiaDAO;
import unipacifico.edu.pasantia.logica.Pasantia;

public class gestionPasantias extends javax.swing.JFrame {

    

    
    public gestionPasantias() {
        initComponents();
        listaPasantia = new ArrayList<Pasantia>();
        guardarPasantia();
        pintarTabla();
        tablaPasantia.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
               tablaSeleccionFila(lse);
           }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoCodigoP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNombreP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoFechainicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoFechafinalizacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoNumeroPasantes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoNumeroConvenioMacro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        botonRegistroPasantia = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPasantia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jLabel1.setText("Gestion Pasantias");

        jLabel2.setText("Codigo");

        campoCodigoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoPActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre Empresa");

        campoNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombrePActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha Inicio");

        jLabel5.setText("Feha Finalizacion");

        campoFechafinalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechafinalizacionActionPerformed(evt);
            }
        });

        jLabel6.setText("Numero Pasantes");

        campoNumeroPasantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroPasantesActionPerformed(evt);
            }
        });

        jLabel7.setText("Descripcion");

        jLabel8.setText("Numero Convenio Macro");

        jLabel9.setText("Estado");

        campoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstadoActionPerformed(evt);
            }
        });

        botonRegistroPasantia.setText("Registrar");
        botonRegistroPasantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroPasantiaActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");

        jButton3.setText("Inactivar");

        tablaPasantia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre Empresa", "Fecha Inicio", "Fecha Finalizacion", "Numero Convenio", "Descripcion", "Numero Pasantes", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaPasantia);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(botonRegistroPasantia)
                        .addGap(80, 80, 80)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campoCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoFechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(49, 49, 49)
                                .addComponent(campoNumeroConvenioMacro, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(22, 22, 22)
                                        .addComponent(campoFechafinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3)
                                            .addComponent(campoNumeroPasantes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(1, 1, 1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNumeroConvenioMacro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoFechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(campoFechafinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(campoNumeroPasantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRegistroPasantia)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void botonRegistroPasantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroPasantiaActionPerformed
     String codigoP = campoCodigoP.getText(); 
     String nombreP = campoNombreP.getText();
     String fechainicio = campoFechainicio.getText();
     String fechafinalizacion = campoFechafinalizacion.getText();
     String descripcion = campoDescripcion.getText();
     String estado = campoEstado.getText();
     String numeroPasantes= campoNumeroPasantes.getText();
     String numeroConvenioMacro= campoNumeroConvenioMacro.getText();
     
     Pasantia pas = new Pasantia(codigoP, nombreP, fechainicio, fechafinalizacion, descripcion, estado, numeroPasantes, numeroConvenioMacro);
     listaPasantia.add(pas);
     try{
       PasantiaDAO dao = new PasantiaDAO();
       dao.guardar(listaPasantia);
     
       catch(IOExcepcion error){
           JOptionPane.showMessageDialog(null,"no se pudo almacenar pasante");
               }
       pintarTabla();
     }  catch (IOException ex) {  
            Logger.getLogger(gestionPasantias.class.getName()).log(Level.SEVERE, null, ex);
        }  
            
        

            
    }//GEN-LAST:event_botonRegistroPasantiaActionPerformed

    private void campoCodigoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoPActionPerformed

    private void campoNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombrePActionPerformed

    private void campoFechafinalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechafinalizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechafinalizacionActionPerformed

    private void campoNumeroPasantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroPasantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroPasantesActionPerformed

    private void campoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEstadoActionPerformed
    {
    }
     public void guardarPasantia(){
     try{
         PasantiaDAO dao = new PasantiaDAO();
         listaPasantia = dao.leer();
      }
      catch(IOException error){ error.printStackTrace();}
      catch(ClassNotFoundException errorTipo){errorTipo.printStackTrace();}
    }
     
     
     
      public void pintarTabla(){
      String tabla []=new String[]{"CodigoP", "NombreP", "Descripcion", "Fechainicio","Fechafinalizacion"};
      int filas = listaPasantia.size();
      String[][]valores= new String[filas][7];
      int contador =0; 
     for (Pasantia Pasante: listaPasantia){
         valores[contador][0]=Pasante.getCodigoP();
         valores[contador][1]=Pasante.getNombreP();
         valores[contador][2]=Pasante.getDescripcion();
         valores[contador][3]=Pasante.getFechainicio();
         valores[contador][4]=Pasante.getFechaFinalizaion();
          valores[contador][5]=Pasante.getNumeroPasantes();
         valores[contador][6]=Pasante.getNumeroConvenioMacro();
        contador++; 
     }
     
          DefaultTableModel modeloTabla= new DefaultTableModel(valores,tabla);
        
        tablaPasantia.setModel(modeloTabla);
       
            
}
      
    

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistroPasantia;
    private javax.swing.JTextField campoCodigoP;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoFechafinalizacion;
    private javax.swing.JTextField campoFechainicio;
    private javax.swing.JTextField campoNombreP;
    private javax.swing.JTextField campoNumeroConvenioMacro;
    private javax.swing.JTextField campoNumeroPasantes;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPasantia;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pasantia> listaPasantia;
    private Pasantia pasanteSeleccionado;
    private int filaSeleccionada= -1;

    private Pasantia Pasasantia(String codigoP, String nombreP, String descripcion, String fechainicio, String fechafinalizacion) {
        
    
